"use client";
import { useEffect, useMemo, useState } from "react";

const STORAGE_KEY="telecomPMv03";
const emptyData={projects:[],production:[],issues:[],risks:[],qc:[],settings:{dailyTarget:1800}};
const sampleData={
 projects:[{id:"p1",name:"Sample FTTH Project",customer:"Demo Customer",contractor:"Demo Contractor",market:"Illinois",type:"FTTH / OSP",start:"2026-10-01",target:"2026-12-01",planned:25000,status:"Active"}],
 production:[{id:"pr1",date:"2026-10-01",crew:"HDD Crew 01",area:"Area 1",span:"101",activity:"HDD / Conduit",qty:620,unit:"LF",status:"Complete",notes:"Sample record"}],
 issues:[{id:"i1",title:"Sample utility conflict",area:"Area 1",span:"101",priority:"High",owner:"CM",status:"Open",action:"Verify conflict and revise path"}],
 risks:[{id:"r1",title:"Sample permit delay",area:"Area 1",probability:"Medium",impact:"High",owner:"PM",status:"Open",response:"Mitigate"}],
 qc:[{id:"q1",title:"Sample depth verification",area:"Area 1",span:"101",owner:"CI",status:"Awaiting Verification",notes:"Verify before closeout"}],
 settings:{dailyTarget:1800}
};
const tabs=["Dashboard","Projects","Production","Issues","Risks","QC","Daily Report","Settings"];
const today=()=>new Date().toISOString().slice(0,10);
const blank={
 project:{name:"",customer:"",contractor:"",market:"",type:"FTTH / OSP",start:"",target:"",planned:"",status:"Active"},
 production:{date:today(),crew:"",area:"",span:"",activity:"HDD / Conduit",qty:"",unit:"LF",status:"Active",notes:""},
 issue:{title:"",area:"",span:"",priority:"High",owner:"CM",status:"Open",action:""},
 risk:{title:"",area:"",probability:"Medium",impact:"High",owner:"PM",status:"Open",response:"Mitigate"},
 qc:{title:"",area:"",span:"",owner:"CI",status:"Open",notes:"",locationLabel:"",latitude:"",longitude:"",photo:"",photoName:""}
};
const keyFor={project:"projects",production:"production",issue:"issues",risk:"risks",qc:"qc"};
const clone=x=>JSON.parse(JSON.stringify(x));
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;

function Card({label,value,sub,onClick}){return <button className="stat card" onClick={onClick}><span className="label">{label}</span><span className="value">{value}</span><span className="sub">{sub}</span></button>}
function Field({label,name,value,onChange,type="text",options,required=false}){return <label className="field"><span>{label}</span>{options?<select name={name} value={value??""} onChange={onChange} required={required}>{options.map(x=><option key={x}>{x}</option>)}</select>:<input type={type} name={name} value={value??""} onChange={onChange} required={required}/>}</label>}
function Modal({title,children,onClose}){return <div className="shade" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><h2>{title}</h2><button className="ghost" onClick={onClose} aria-label="Close">✕</button></div>{children}</div></div>}

export default function Home(){
 const [data,setData]=useState(emptyData),[tab,setTab]=useState("Dashboard"),[modal,setModal]=useState(null),[form,setForm]=useState(blank.production),[editId,setEditId]=useState(null),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){const parsed=JSON.parse(saved);setData({...clone(emptyData),...parsed,settings:{...emptyData.settings,...(parsed.settings||{})}})}}catch(e){console.error(e)}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEY,JSON.stringify(data))},[data,loaded]);
 const date=today(),prodToday=data.production.filter(x=>x.date===date),total=prodToday.reduce((s,x)=>s+(Number(x.qty)||0),0),target=Number(data.settings?.dailyTarget)||0;
 const openIssues=data.issues.filter(x=>x.status!=="Closed"),openRisks=data.risks.filter(x=>x.status!=="Closed"),openQc=data.qc.filter(x=>!["Closed","Verified"].includes(x.status));
 const flash=t=>{setNotice(t);setTimeout(()=>setNotice(""),2200)};
 const openAdd=kind=>{setEditId(null);setForm({...blank[kind],...(kind==="production"?{date:today()}: {})});setModal(kind)};
 const openEdit=(kind,item)=>{setEditId(item.id);setForm({...item});setModal(kind)};
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const addQcPhoto=async e=>{const file=e.target.files?.[0];if(!file)return;try{const photo=await compressImage(file);setForm(f=>({...f,photo,photoName:file.name}));flash("Photo attached")}catch{flash("Could not attach photo")};e.target.value=""};
 const removeQcPhoto=()=>setForm(f=>({...f,photo:"",photoName:""}));
 const getQcLocation=()=>{if(!navigator.geolocation){flash("Location is not supported on this device");return}flash("Getting location…");navigator.geolocation.getCurrentPosition(pos=>{setForm(f=>({...f,latitude:pos.coords.latitude.toFixed(6),longitude:pos.coords.longitude.toFixed(6)}));flash("Location captured")},err=>{flash(err.code===1?"Location permission was denied":"Could not get location")},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})};
 const save=e=>{e.preventDefault();const key=keyFor[modal];if(!key)return;let record={...form};if(modal==="production")record.qty=Number(record.qty)||0;if(modal==="project")record.planned=Number(record.planned)||0;if(editId){setData(d=>({...d,[key]:d[key].map(x=>x.id===editId?{...record,id:editId}:x)}));flash("Entry updated")}else{setData(d=>({...d,[key]:[...d[key],{...record,id:uid()}]}));flash("Entry added")}setModal(null)};
 const remove=(key,id)=>{if(!confirm("Delete this entry? This cannot be undone."))return;setData(d=>({...d,[key]:d[key].filter(x=>x.id!==id)}));flash("Entry deleted")};
 const report=useMemo(()=>`DAILY TELECOM CONSTRUCTION REPORT\nDate: ${date}\n\nProduction: ${total.toLocaleString()} LF/units recorded across ${prodToday.length} entries.\nOpen Issues: ${openIssues.length}\nOpen Risks: ${openRisks.length}\nOpen QC Items: ${openQc.length}\n\nFIELD PRODUCTION\n${prodToday.map(x=>`• ${x.crew} | ${x.area}${x.span?` / Span ${x.span}`:""} | ${x.activity} | ${x.qty} ${x.unit} | ${x.status}${x.notes?` | ${x.notes}`:""}`).join("\n")||"No production entered today."}\n\nISSUES\n${openIssues.map(x=>`• ${x.priority}: ${x.title} | ${x.area} ${x.span||""} | Owner: ${x.owner} | ${x.status} | ${x.action}`).join("\n")||"None open."}\n\nRISKS\n${openRisks.map(x=>`• ${x.title} | P:${x.probability} I:${x.impact} | Owner: ${x.owner} | ${x.status} | Response: ${x.response}`).join("\n")||"None open."}\n\nQC / PUNCH\n${openQc.map(x=>`• ${x.title} | ${x.area} ${x.span||""} | ${x.status} | Owner: ${x.owner}${x.locationLabel?` | Location: ${x.locationLabel}`:""}${x.latitude&&x.longitude?` | GPS: ${x.latitude},${x.longitude}`:""}${x.photo?` | Photo attached`:""}${x.notes?` | ${x.notes}`:""}`).join("\n")||"None open."}`,[data,total,date]);
 const copy=async()=>{try{await navigator.clipboard.writeText(report);flash("Daily report copied")}catch{flash("Copy failed. Select the report text manually.")}};
 const clearAll=()=>{if(confirm("Delete ALL project data stored on this device?")){setData(clone(emptyData));localStorage.removeItem(STORAGE_KEY);flash("All data cleared")}};
 const loadSample=()=>{if(confirm("Replace current data with sample data?")){setData(clone(sampleData));flash("Sample data loaded")}};
 const setTarget=e=>setData(d=>({...d,settings:{...d.settings,dailyTarget:Number(e.target.value)||0}}));
 if(!loaded)return <main><section className="panel"><p>Loading field hub…</p></section></main>;
 return <main>
  {notice&&<div className="toast">{notice}</div>}
  <header><div><div className="eyebrow">TELECOM CONSTRUCTION PROJECT MANAGEMENT</div><h1>Telecom PM Field Hub</h1><p>Field-first FTTH / OSP project management • v0.4</p></div><div className="badge">FTTH / OSP</div></header>
  <nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==="Dashboard"&&<><section className="grid stats"><Card label="Production Today" value={`${total.toLocaleString()} LF`} sub={target?`${Math.round(total/target*100)}% of ${target.toLocaleString()} LF target`:"Set target in Settings"} onClick={()=>setTab("Production")}/><Card label="Active Projects" value={data.projects.filter(x=>x.status==="Active").length} sub="Tap to manage" onClick={()=>setTab("Projects")}/><Card label="Open Issues" value={openIssues.length} sub={`${openIssues.filter(x=>x.priority==="Critical").length} critical`} onClick={()=>setTab("Issues")}/><Card label="Open Risks" value={openRisks.length} sub={`${openRisks.filter(x=>x.impact==="High").length} high impact`} onClick={()=>setTab("Risks")}/><Card label="QC Items" value={openQc.length} sub={`${openQc.filter(x=>x.status==="Awaiting Verification").length} awaiting verification`} onClick={()=>setTab("QC")}/></section><section className="two"><div className="panel"><div className="panelHead"><h2>Today's Field Production</h2><button onClick={()=>openAdd("production")}>+ Entry</button></div>{prodToday.map(x=><div className="row" key={x.id}><div><b>{x.crew||"Unnamed crew"}</b><small>{x.area} {x.span&&`• Span ${x.span}`} • {x.activity}</small></div><strong>{x.qty} {x.unit}</strong></div>)}{!prodToday.length&&<p className="muted">No production entered today.</p>}</div><div className="panel"><div className="panelHead"><h2>PM Health</h2><span>Live from your entries</span></div><div className="health"><p><b>Production</b><span className={target&&total>=target?"good":"warn"}>{target?`${Math.round(total/target*100)}% target`:"No target"}</span></p><p><b>Issues</b><span className={openIssues.some(x=>x.priority==="Critical")?"bad":"good"}>{openIssues.length} open</span></p><p><b>Risk</b><span className={openRisks.some(x=>x.impact==="High")?"warn":"good"}>{openRisks.length} open</span></p><p><b>Quality</b><span className={openQc.length?"warn":"good"}>{openQc.length} open</span></p></div></div></section></>}
  {tab==="Projects"&&<List title="Projects" add={()=>openAdd("project")} headers={["Project","Customer / Contractor","Market","Type","Status"]} rows={data.projects.map(x=>[x.name,`${x.customer||"—"} / ${x.contractor||"—"}`,x.market,x.type,x.status])} items={data.projects} edit={x=>openEdit("project",x)} del={id=>remove("projects",id)}/>} 
  {tab==="Production"&&<List title="Daily Production" add={()=>openAdd("production")} headers={["Date","Crew","Area / Span","Activity","Production","Status"]} rows={data.production.map(x=>[x.date,x.crew,`${x.area}${x.span?` / ${x.span}`:""}`,x.activity,`${x.qty} ${x.unit}`,x.status])} items={data.production} edit={x=>openEdit("production",x)} del={id=>remove("production",id)}/>} 
  {tab==="Issues"&&<List title="Issue Log" add={()=>openAdd("issue")} headers={["Issue","Area / Span","Priority","Owner","Status","Action"]} rows={data.issues.map(x=>[x.title,`${x.area} ${x.span||""}`,x.priority,x.owner,x.status,x.action])} items={data.issues} edit={x=>openEdit("issue",x)} del={id=>remove("issues",id)}/>} 
  {tab==="Risks"&&<List title="Risk Register" add={()=>openAdd("risk")} headers={["Risk","Area","Probability","Impact","Owner","Status","Response"]} rows={data.risks.map(x=>[x.title,x.area,x.probability,x.impact,x.owner,x.status,x.response])} items={data.risks} edit={x=>openEdit("risk",x)} del={id=>remove("risks",id)}/>} 
  {tab==="QC"&&<QCList items={data.qc} add={()=>openAdd("qc")} edit={x=>openEdit("qc",x)} del={id=>remove("qc",id)}/>} 
  {tab==="Daily Report"&&<section className="panel report"><div className="panelHead"><h2>Daily PM Report</h2><button onClick={copy}>Copy Report</button></div><pre>{report}</pre></section>}
  {tab==="Settings"&&<section className="panel settings"><div className="panelHead"><h2>Settings & Data</h2></div><label className="field"><span>Daily production target (LF)</span><input type="number" value={data.settings?.dailyTarget??1800} onChange={setTarget}/></label><div className="settingsActions"><button onClick={loadSample}>Load Sample Data</button><button className="danger" onClick={clearAll}>Clear All Data</button></div><p className="muted">Your entries are stored in this browser on this device. Sample data is optional and never reloads itself after you delete it.</p></section>}
  <footer>Telecom PM Field Hub • v0.4 • Local device storage</footer>
  {modal&&<Modal title={`${editId?"Edit":"Add"} ${modal[0].toUpperCase()+modal.slice(1)}`} onClose={()=>setModal(null)}><EntryForm kind={modal} form={form} change={change} save={save} editing={!!editId} addQcPhoto={addQcPhoto} removeQcPhoto={removeQcPhoto} getQcLocation={getQcLocation}/></Modal>}
 </main>
}
function List({title,add,headers,rows,items,edit,del}){return <section className="panel list"><div className="panelHead"><h2>{title}</h2><button onClick={add}>+ Add</button></div><div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={items[i].id}>{r.map((v,j)=><td key={j}>{v||"—"}</td>)}<td><div className="actions"><button className="ghost" onClick={()=>edit(items[i])}>Edit</button><button className="danger ghost" onClick={()=>del(items[i].id)}>Delete</button></div></td></tr>)}</tbody></table></div>{!rows.length&&<p className="muted empty">Nothing here yet. A suspiciously peaceful construction project.</p>}</section>}
function EntryForm({kind,form,change,save,editing,addQcPhoto,removeQcPhoto,getQcLocation}){return <form onSubmit={save} className="form">
 {kind==="project"&&<><Field label="Project name" name="name" value={form.name} onChange={change} required/><Field label="Customer" name="customer" value={form.customer} onChange={change}/><Field label="GC / Contractor" name="contractor" value={form.contractor} onChange={change}/><Field label="Market / Location" name="market" value={form.market} onChange={change}/><Field label="Type" name="type" value={form.type} onChange={change} options={["FTTH / OSP","Wireless","Fiber Backbone","Other"]}/><Field label="Start" name="start" type="date" value={form.start} onChange={change}/><Field label="Target completion" name="target" type="date" value={form.target} onChange={change}/><Field label="Planned footage" name="planned" type="number" value={form.planned} onChange={change}/><Field label="Status" name="status" value={form.status} onChange={change} options={["Active","Planning","On Hold","Complete","Closed"]}/></>}
 {kind==="production"&&<><Field label="Date" name="date" type="date" value={form.date} onChange={change} required/><Field label="Crew" name="crew" value={form.crew} onChange={change} required/><Field label="Area" name="area" value={form.area} onChange={change}/><Field label="Span" name="span" value={form.span} onChange={change}/><Field label="Activity" name="activity" value={form.activity} onChange={change} options={["HDD / Conduit","Fiber Placement","Potholing","Handhole / Vault","Splicing","Restoration","QC / As-Built"]}/><Field label="Production quantity" name="qty" type="number" value={form.qty} onChange={change}/><Field label="Unit" name="unit" value={form.unit} onChange={change} options={["LF","EA","Locations","HH","Vaults"]}/><Field label="Status" name="status" value={form.status} onChange={change} options={["Active","Complete","Delayed","Blocked"]}/><Field label="Notes" name="notes" value={form.notes} onChange={change}/></>}
 {kind==="issue"&&<><Field label="Issue" name="title" value={form.title} onChange={change} required/><Field label="Area" name="area" value={form.area} onChange={change}/><Field label="Span" name="span" value={form.span} onChange={change}/><Field label="Priority" name="priority" value={form.priority} onChange={change} options={["Critical","High","Medium","Low"]}/><Field label="Owner" name="owner" value={form.owner} onChange={change}/><Field label="Status" name="status" value={form.status} onChange={change} options={["Open","In Progress","Blocked","Closed"]}/><Field label="Action" name="action" value={form.action} onChange={change}/></>}
 {kind==="risk"&&<><Field label="Risk" name="title" value={form.title} onChange={change} required/><Field label="Area" name="area" value={form.area} onChange={change}/><Field label="Probability" name="probability" value={form.probability} onChange={change} options={["High","Medium","Low"]}/><Field label="Impact" name="impact" value={form.impact} onChange={change} options={["High","Medium","Low"]}/><Field label="Owner" name="owner" value={form.owner} onChange={change}/><Field label="Status" name="status" value={form.status} onChange={change} options={["Open","Monitoring","Mitigated","Closed"]}/><Field label="Response" name="response" value={form.response} onChange={change} options={["Mitigate","Avoid","Transfer","Accept","Escalate"]}/></>}
 {kind==="qc"&&<><Field label="QC / Punch item" name="title" value={form.title} onChange={change} required/><Field label="Area" name="area" value={form.area} onChange={change}/><Field label="Span" name="span" value={form.span} onChange={change}/><Field label="Owner" name="owner" value={form.owner} onChange={change}/><Field label="Status" name="status" value={form.status} onChange={change} options={["Open","In Progress","Awaiting Verification","Verified","Closed"]}/><Field label="Location / address (optional)" name="locationLabel" value={form.locationLabel} onChange={change}/><div className="qcTools"><button type="button" className="toolBtn" onClick={getQcLocation}>📍 Use Current Location</button>{form.latitude&&form.longitude&&<a className="mapLink" target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${form.latitude},${form.longitude}`}>Open map</a>}</div>{form.latitude&&form.longitude&&<div className="gpsReadout">GPS: {form.latitude}, {form.longitude}</div>}<div className="photoTools"><label className="toolBtn fileBtn">📷 Take Photo<input type="file" accept="image/*" capture="environment" onChange={addQcPhoto}/></label><label className="toolBtn fileBtn">🖼 Upload Photo<input type="file" accept="image/*" onChange={addQcPhoto}/></label></div>{form.photo&&<div className="photoPreview"><img src={form.photo} alt="QC attachment preview"/><button type="button" className="danger ghost" onClick={removeQcPhoto}>Remove Photo</button></div>}<Field label="Notes" name="notes" value={form.notes} onChange={change}/></>}
 <button className="save" type="submit">{editing?"Save Changes":"Add Entry"}</button></form>}


function QCList({items,add,edit,del}){return <section className="panel list"><div className="panelHead"><h2>QC / Punch List</h2><button onClick={add}>+ Add</button></div>{!items.length&&<p className="muted empty">Nothing here yet. A suspiciously peaceful construction project.</p>}<div className="qcCards">{items.map(x=><article className="qcCard" key={x.id}>{x.photo&&<button className="photoThumb" onClick={()=>window.open(x.photo,"_blank")}><img src={x.photo} alt={x.title||"QC photo"}/></button>}<div className="qcBody"><div className="qcTop"><strong>{x.title||"Untitled QC item"}</strong><span className="statusPill">{x.status||"Open"}</span></div><div className="qcMeta">{x.area||"No area"}{x.span?` • Span ${x.span}`:""}{x.owner?` • ${x.owner}`:""}</div>{x.locationLabel&&<div className="qcLocation">📍 {x.locationLabel}</div>}{x.latitude&&x.longitude&&<a className="mapLink" target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${x.latitude},${x.longitude}`}>📍 GPS {x.latitude}, {x.longitude}</a>}{x.notes&&<p className="qcNotes">{x.notes}</p>}<div className="actions"><button className="ghost" onClick={()=>edit(x)}>Edit</button><button className="danger ghost" onClick={()=>del(x.id)}>Delete</button></div></div></article>)}</div></section>}

function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",.72))};img.src=reader.result};reader.readAsDataURL(file)})}
